version: "3.9"

networks:
  app_network:
    driver: bridge


services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Expose FastAPI to the public
    restart: always
    networks:
      - app_network

  discord_bot:
    build: ./discord_bot
    env_file:
      - .env
    environment:
      - API_URL=${API_URL}
      - DISCORD_BOT_TOKEN=${TOKEN_DISCORD_BOT}
    depends_on:
      - backend
    restart: always
    networks:
      - app_network


  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./backend/Modelfile.md:/root/Modelfile.md  # Mount Modelfile
    entrypoint: [
      "/bin/sh",
      "-c",
      "ollama serve && ollama create custom_m -f /root/Modelfile.md && ollama run custom_m"]
    networks:
      - app_network

volumes:
  ollama_data:
